# Generated by Django 5.2.5 on 2025-10-14 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloDonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObjeto', models.CharField(max_length=150, verbose_name='Nombre del Objeto')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaVencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Stock Actual')),
            ],
            options={
                'verbose_name': 'Artículo Donado',
                'verbose_name_plural': 'Artículos Donados',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDonante', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('EMPRESA', 'Empresa'), ('ORGANIZACION', 'Organización')], default='INDIVIDUAL', max_length=20, verbose_name='Tipo de Donante')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Donante',
                'verbose_name_plural': 'Donantes',
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDonacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Donación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Notas de la Donación')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad Donada')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donaciones_recibidas', to='gestion_donaciones.articulodonado')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donaciones_realizadas', to='gestion_donaciones.donante')),
            ],
            options={
                'verbose_name': 'Donación Recibida',
                'verbose_name_plural': 'Donaciones Recibidas',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad Entregada')),
                ('nombreResponsable', models.CharField(max_length=100, verbose_name='Responsable de la Entrega')),
                ('fechaEntrega', models.DateField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to='gestion_donaciones.articulodonado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_recibidas', to='gestion_donaciones.beneficiario')),
            ],
            options={
                'verbose_name': 'Entrega Realizada',
                'verbose_name_plural': 'Entregas Realizadas',
            },
        ),
    ]
