# Generated by Django 5.2.5 on 2025-12-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_donaciones', '0002_donante_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='articulodonado',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulodonado',
            name='nombreObjeto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fechaDonacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='tipoDonante',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('EMPRESA', 'Empresa'), ('ORGANIZACION', 'Organización')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fechaEntrega',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='nombreResponsable',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_donaciones.articulodonado')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_donaciones.entrega')),
            ],
            options={
                'verbose_name': 'Detalle de Entrega',
                'verbose_name_plural': 'Detalles de Entrega',
            },
        ),
    ]
