# Generated by Django 5.2.5 on 2025-12-05 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_donaciones', '0003_remove_entrega_articulo_remove_entrega_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulodonado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='beneficiario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detalleentrega',
            options={'verbose_name': 'Detalle de Entrega', 'verbose_name_plural': 'Detalles de Entregas'},
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ['-fechaEntrega'], 'verbose_name': 'Entrega', 'verbose_name_plural': 'Entregas'},
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='representante',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='user',
        ),
        migrations.AlterField(
            model_name='articulodonado',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulodonado',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='articulodonado',
            name='nombreObjeto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleentrega',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_donaciones.articulodonado'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_donaciones.articulodonado'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_donaciones.donante'),
        ),
        migrations.AlterField(
            model_name='donante',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_donaciones.beneficiario'),
        ),
    ]
