# Generated by Django 5.2.5 on 2025-12-05 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_donaciones', '0004_alter_articulodonado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrega',
            name='donacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_donaciones.donacion'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='estado',
            field=models.CharField(default='Recibido', max_length=50),
        ),
        migrations.AddField(
            model_name='donacion',
            name='uuid_seguimiento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazabilidad', to='gestion_donaciones.donacion')),
            ],
        ),
    ]
