# Generated by Django 5.2.5 on 2025-12-05 16:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_donaciones', '0005_detalleentrega_donacion_donacion_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Detalle de Donación',
                'verbose_name_plural': 'Detalles de Donaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='articulodonado',
            options={'ordering': ['nombreObjeto'], 'verbose_name': 'Artículo Donado', 'verbose_name_plural': 'Artículos Donados'},
        ),
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'ordering': ['nombre'], 'verbose_name': 'Beneficiario', 'verbose_name_plural': 'Beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={'ordering': ['-fechaDonacion'], 'verbose_name': 'Donación', 'verbose_name_plural': 'Donaciones'},
        ),
        migrations.AlterModelOptions(
            name='donante',
            options={'ordering': ['nombre'], 'verbose_name': 'Donante', 'verbose_name_plural': 'Donantes'},
        ),
        migrations.AlterModelOptions(
            name='trazabilidad',
            options={'ordering': ['fecha'], 'verbose_name': 'Registro de Trazabilidad', 'verbose_name_plural': 'Registros de Trazabilidad'},
        ),
        migrations.AlterUniqueTogether(
            name='detalleentrega',
            unique_together={('entrega', 'articulo')},
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='articulodonado',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTOS', 'Alimentos'), ('ROPA', 'Ropa y Calzado'), ('HIGIENE', 'Productos de Higiene'), ('MEDICAMENTOS', 'Medicamentos'), ('EDUCACION', 'Material Educativo'), ('ELECTRODOMESTICOS', 'Electrodomésticos'), ('MUEBLES', 'Muebles'), ('JUGUETES', 'Juguetes'), ('OTROS', 'Otros')], default='OTROS', help_text='Categoría del artículo', max_length=50),
        ),
        migrations.AddField(
            model_name='articulodonado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articulodonado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulodonado',
            name='unidad_medida',
            field=models.CharField(choices=[('UNIDAD', 'Unidad(es)'), ('KG', 'Kilogramos'), ('LITRO', 'Litros'), ('CAJA', 'Caja(s)'), ('PAQUETE', 'Paquete(s)'), ('BOLSA', 'Bolsa(s)'), ('PAR', 'Par(es)'), ('METRO', 'Metro(s)')], default='UNIDAD', help_text='Unidad de medida para contar el artículo', max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donacion',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donacion',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas sobre la donación'),
        ),
        migrations.AddField(
            model_name='donante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donante',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='COMPLETADA', max_length=20),
        ),
        migrations.AddField(
            model_name='entrega',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='uuid_seguimiento',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='articulodonado',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='articulodonado',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='detalleentrega',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En Proceso'), ('ALMACENADO', 'Almacenado'), ('EN_ENTREGA', 'En Entrega'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='uuid_seguimiento',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='donante',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='donacion',
            index=models.Index(fields=['uuid_seguimiento'], name='gestion_don_uuid_se_e72ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='donacion',
            index=models.Index(fields=['-fechaDonacion'], name='gestion_don_fechaDo_aa6423_idx'),
        ),
        migrations.AddField(
            model_name='detalledonacion',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_donaciones.articulodonado'),
        ),
        migrations.AddField(
            model_name='detalledonacion',
            name='donacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_donaciones.donacion'),
        ),
        migrations.AddField(
            model_name='detalleentrega',
            name='detalle_donacion',
            field=models.ForeignKey(blank=True, help_text='Detalle de donación original', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_donaciones.detalledonacion'),
        ),
        migrations.RemoveField(
            model_name='detalleentrega',
            name='donacion',
        ),
        migrations.AlterUniqueTogether(
            name='detalledonacion',
            unique_together={('donacion', 'articulo')},
        ),
    ]
