# Generated by Django 5.2.5 on 2025-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_donaciones', '0006_detalledonacion_alter_articulodonado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
